### ISSUE TITLE
Rui...

### ISSUE THREAD

**Issue by pedrosanta** [ruiramos/textareaplease#1]
...o que é isto?

![](https://media.giphy.com/media/CKHo4ZlaudKdG/giphy.gif)

**Comment by ruiramos** [comment]
so vi isto agora que tem nao gostas? ja tem mais features

**Comment by pedrosanta** [comment]
Gosto. Já dei estrelinha, vou contribuir. Gosto do design.

**Comment by pedrosanta** [comment]
(Depois responde só à pergunta para fazer close ao issue. É assim que se faz no desenvolvimento do software.)

**Comment by ruiramos** [comment]
ok desculpa ainda estou a aprender. e' um repositorio.
